### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by lumisoftusa** [UdaraAlwis/XFSegmentedControl#1]
Hi i am loving to use this component great job , Please guide me is there any way to add image inside segment button.

Regards

Atif

**Comment by UdaraAlwis** [comment]
Thanks for the feedback :) 

It's very simple to add an image to the Tab actually,

1. Create your custom model to populate the TabButton with Image and Text
2. Add the Image into the TabButton.xaml view, 
3. Add a parameter to the TabButton() constructor passing the image object and assign it to the image view you added in the first step.
4. Change the TabButtonsSourceProperty type to object, to be used with your custom model
5. inside OnTabButtonsPropertyChanged extract the object from the list and cast it to your custom model's object, retrieve the image and text and pass it into the constructor of the TabButton(), inside the population loop I have implemented there.
6. Bind your data source for the Tabs with the custom model you created in your Page and you're done!

There you go as simple as it gets. Hope it helps. Cheers!
